### PR TITLE
Update manifest.webapp

### PR DESCRIPTION
**Pull request by Airon90**
Added Italian (it) and Esperanto (eo) localizations

### CODE REVIEW

**Comment by takenspc** [comment]
I would like you to just confirm that these translations don't contain translations of "Twitter" in "name".
If they don't, I will merge this PR.

**Comment by Airon90** [comment]
The original "name" variable is "Tweet this page" so I translated the verb "to tweet" into Italian and into Esperanto. Trademark names must not be translated or changed, in fact I left "Twitter" untranslated in both "description" variable.
Maybe I misunderstood your comment and I need help to understand what you meant ^^

**Comment by takenspc** [comment]
I meant that the app name doesn't contain  "Twitter" as Twitter prohibits.

https://about.twitter.com/press/brand-assets

> Don’t:
> - Use Twitter in the name of your website, application or product.

The below is OK. So I will merge PRs.

 >  I translated the verb "to tweet" into Italian and into Esperanto.

**Comment by Airon90** [comment]
Thank you very much for your clarification :)

**Comment by takenspc** [comment]
The new version which includes your translations is now available.
https://marketplace.firefox.com/app/pstttwtr/

**Comment by Airon90** [comment]
:+1: thank you!

**Pull request merged**
